Build:
  stage: build
#  image: docker:latest
  before_script:
    - docker login $DOCKER_REPO --username $DOCKER_USER --password $DOCKER_PASS
  variables:
    DOCKER_REGISTRY_URL: "https://$DOCKER_REPO"
    DOCKER_REGISTRY_USER: $DOCKER_USER
    DOCKER_REGISTRY_PASSWORD: $DOCKER_PASS
  tags:
    - test-runner
  script:
    - echo "Do your build here"
    - docker build -t $DOCKER_REPO/$(echo $CI_PROJECT_PATH | tr A-Z a-z) .
    - docker push $DOCKER_REPO/$(echo $CI_PROJECT_PATH | tr A-Z a-z)

Junit-test1:
  stage: test
  tags:
    - test-runner
  script:
    - echo "Do a test here"
    - echo "For example run a test suite"
    - pip install pytest==2.9.1
    - pytest app/app.py

Deploy:
  stage: deploy
  before_script:
    - docker login $DOCKER_REPO --username $DOCKER_USER --password $DOCKER_PASS
  variables:
    DOCKER_REGISTRY_URL: "https://$DOCKER_REPO"
    DOCKER_REGISTRY_USER: $DOCKER_USER
    DOCKER_REGISTRY_PASSWORD: $DOCKER_PASS
  tags:
    - test-runner
  script:
    - echo "Do your deploy here"
    - docker run -ti $DOCKER_REPO/$(echo $CI_PROJECT_PATH | tr A-Z a-z)

